// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: aaa.proto

package pb_aaa

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Register User Request
type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	MobileNumber  string                 `protobuf:"bytes,3,opt,name=mobile_number,json=mobileNumber,proto3" json:"mobile_number,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_aaa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetMobileNumber() string {
	if x != nil {
		return x.MobileNumber
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// Register User Response
type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UserData              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Error         []string               `protobuf:"bytes,4,rep,name=error,proto3" json:"error,omitempty"`
	StatusCode    int32                  `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_aaa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterUserResponse) GetData() *UserData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RegisterUserResponse) GetError() []string {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RegisterUserResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RegisterUserResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Login Request
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_aaa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Login Response
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UserData              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Error         []string               `protobuf:"bytes,4,rep,name=error,proto3" json:"error,omitempty"`
	StatusCode    int32                  `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_aaa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetData() *UserData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LoginResponse) GetError() []string {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *LoginResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *LoginResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Get User by ID Request
type GetUserByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdRequest) Reset() {
	*x = GetUserByIdRequest{}
	mi := &file_aaa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdRequest) ProtoMessage() {}

func (x *GetUserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserByIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Get User by ID Response
type GetUserByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UserData              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Error         []string               `protobuf:"bytes,4,rep,name=error,proto3" json:"error,omitempty"`
	StatusCode    int32                  `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdResponse) Reset() {
	*x = GetUserByIdResponse{}
	mi := &file_aaa_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdResponse) ProtoMessage() {}

func (x *GetUserByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIdResponse) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserByIdResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetUserByIdResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserByIdResponse) GetData() *UserData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetUserByIdResponse) GetError() []string {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetUserByIdResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetUserByIdResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Get User by Mobile Number Request
type GetUserByMobileNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MobileNumber  string                 `protobuf:"bytes,1,opt,name=mobile_number,json=mobileNumber,proto3" json:"mobile_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByMobileNumberRequest) Reset() {
	*x = GetUserByMobileNumberRequest{}
	mi := &file_aaa_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByMobileNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByMobileNumberRequest) ProtoMessage() {}

func (x *GetUserByMobileNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByMobileNumberRequest.ProtoReflect.Descriptor instead.
func (*GetUserByMobileNumberRequest) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserByMobileNumberRequest) GetMobileNumber() string {
	if x != nil {
		return x.MobileNumber
	}
	return ""
}

// Get User by Mobile Number Response
type GetUserByMobileNumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UserData              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Error         []string               `protobuf:"bytes,4,rep,name=error,proto3" json:"error,omitempty"`
	StatusCode    int32                  `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByMobileNumberResponse) Reset() {
	*x = GetUserByMobileNumberResponse{}
	mi := &file_aaa_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByMobileNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByMobileNumberResponse) ProtoMessage() {}

func (x *GetUserByMobileNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByMobileNumberResponse.ProtoReflect.Descriptor instead.
func (*GetUserByMobileNumberResponse) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserByMobileNumberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetUserByMobileNumberResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserByMobileNumberResponse) GetData() *UserData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetUserByMobileNumberResponse) GetError() []string {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetUserByMobileNumberResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetUserByMobileNumberResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Assign Role to User Request
type AssignRoleToUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleName      string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleToUserRequest) Reset() {
	*x = AssignRoleToUserRequest{}
	mi := &file_aaa_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleToUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleToUserRequest) ProtoMessage() {}

func (x *AssignRoleToUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleToUserRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleToUserRequest) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{8}
}

func (x *AssignRoleToUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignRoleToUserRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

// Assign Role to User Response
type AssignRoleToUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UserData              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Error         []string               `protobuf:"bytes,4,rep,name=error,proto3" json:"error,omitempty"`
	StatusCode    int32                  `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleToUserResponse) Reset() {
	*x = AssignRoleToUserResponse{}
	mi := &file_aaa_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleToUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleToUserResponse) ProtoMessage() {}

func (x *AssignRoleToUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleToUserResponse.ProtoReflect.Descriptor instead.
func (*AssignRoleToUserResponse) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{9}
}

func (x *AssignRoleToUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AssignRoleToUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AssignRoleToUserResponse) GetData() *UserData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AssignRoleToUserResponse) GetError() []string {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *AssignRoleToUserResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AssignRoleToUserResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Validate User Request
type ValidateUserRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ValidationStatus string                 `protobuf:"bytes,2,opt,name=validation_status,json=validationStatus,proto3" json:"validation_status,omitempty"`
	Address          string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	PersonalDetails  *PersonalDetails       `protobuf:"bytes,4,opt,name=personal_details,json=personalDetails,proto3" json:"personal_details,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidateUserRequest) Reset() {
	*x = ValidateUserRequest{}
	mi := &file_aaa_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUserRequest) ProtoMessage() {}

func (x *ValidateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUserRequest.ProtoReflect.Descriptor instead.
func (*ValidateUserRequest) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateUserRequest) GetValidationStatus() string {
	if x != nil {
		return x.ValidationStatus
	}
	return ""
}

func (x *ValidateUserRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ValidateUserRequest) GetPersonalDetails() *PersonalDetails {
	if x != nil {
		return x.PersonalDetails
	}
	return nil
}

// Validate User Response
type ValidateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UserData              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Error         []string               `protobuf:"bytes,4,rep,name=error,proto3" json:"error,omitempty"`
	StatusCode    int32                  `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateUserResponse) Reset() {
	*x = ValidateUserResponse{}
	mi := &file_aaa_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUserResponse) ProtoMessage() {}

func (x *ValidateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUserResponse.ProtoReflect.Descriptor instead.
func (*ValidateUserResponse) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{11}
}

func (x *ValidateUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ValidateUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidateUserResponse) GetData() *UserData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ValidateUserResponse) GetError() []string {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ValidateUserResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ValidateUserResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Create Relationship Request
type CreateRelationshipRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RelatedUserId    string                 `protobuf:"bytes,2,opt,name=related_user_id,json=relatedUserId,proto3" json:"related_user_id,omitempty"`
	RelationshipType string                 `protobuf:"bytes,3,opt,name=relationship_type,json=relationshipType,proto3" json:"relationship_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateRelationshipRequest) Reset() {
	*x = CreateRelationshipRequest{}
	mi := &file_aaa_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRelationshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRelationshipRequest) ProtoMessage() {}

func (x *CreateRelationshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRelationshipRequest.ProtoReflect.Descriptor instead.
func (*CreateRelationshipRequest) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{12}
}

func (x *CreateRelationshipRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateRelationshipRequest) GetRelatedUserId() string {
	if x != nil {
		return x.RelatedUserId
	}
	return ""
}

func (x *CreateRelationshipRequest) GetRelationshipType() string {
	if x != nil {
		return x.RelationshipType
	}
	return ""
}

// Create Relationship Response
type CreateRelationshipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *RelationshipData      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Error         []string               `protobuf:"bytes,4,rep,name=error,proto3" json:"error,omitempty"`
	StatusCode    int32                  `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRelationshipResponse) Reset() {
	*x = CreateRelationshipResponse{}
	mi := &file_aaa_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRelationshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRelationshipResponse) ProtoMessage() {}

func (x *CreateRelationshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRelationshipResponse.ProtoReflect.Descriptor instead.
func (*CreateRelationshipResponse) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{13}
}

func (x *CreateRelationshipResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateRelationshipResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateRelationshipResponse) GetData() *RelationshipData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateRelationshipResponse) GetError() []string {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CreateRelationshipResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CreateRelationshipResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Delete Relationship Request
type DeleteRelationshipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RelatedUserId string                 `protobuf:"bytes,2,opt,name=related_user_id,json=relatedUserId,proto3" json:"related_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRelationshipRequest) Reset() {
	*x = DeleteRelationshipRequest{}
	mi := &file_aaa_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRelationshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRelationshipRequest) ProtoMessage() {}

func (x *DeleteRelationshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRelationshipRequest.ProtoReflect.Descriptor instead.
func (*DeleteRelationshipRequest) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteRelationshipRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteRelationshipRequest) GetRelatedUserId() string {
	if x != nil {
		return x.RelatedUserId
	}
	return ""
}

// Delete Relationship Response
type DeleteRelationshipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         []string               `protobuf:"bytes,3,rep,name=error,proto3" json:"error,omitempty"`
	StatusCode    int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRelationshipResponse) Reset() {
	*x = DeleteRelationshipResponse{}
	mi := &file_aaa_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRelationshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRelationshipResponse) ProtoMessage() {}

func (x *DeleteRelationshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRelationshipResponse.ProtoReflect.Descriptor instead.
func (*DeleteRelationshipResponse) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteRelationshipResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteRelationshipResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteRelationshipResponse) GetError() []string {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *DeleteRelationshipResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeleteRelationshipResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// User Data
type UserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	MobileNumber  string                 `protobuf:"bytes,4,opt,name=mobile_number,json=mobileNumber,proto3" json:"mobile_number,omitempty"`
	IsValidated   bool                   `protobuf:"varint,5,opt,name=is_validated,json=isValidated,proto3" json:"is_validated,omitempty"`
	Roles         []*Role                `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_aaa_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{16}
}

func (x *UserData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserData) GetMobileNumber() string {
	if x != nil {
		return x.MobileNumber
	}
	return ""
}

func (x *UserData) GetIsValidated() bool {
	if x != nil {
		return x.IsValidated
	}
	return false
}

func (x *UserData) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UserData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserData) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Role
type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Permissions   []*Permission          `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_aaa_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{17}
}

func (x *Role) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *Role) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// Permission
type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Actions       []string               `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_aaa_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{18}
}

func (x *Permission) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Permission) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

// Personal Details
type PersonalDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,2,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender        string                 `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode    string                 `protobuf:"bytes,8,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalDetails) Reset() {
	*x = PersonalDetails{}
	mi := &file_aaa_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalDetails) ProtoMessage() {}

func (x *PersonalDetails) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalDetails.ProtoReflect.Descriptor instead.
func (*PersonalDetails) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{19}
}

func (x *PersonalDetails) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *PersonalDetails) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *PersonalDetails) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *PersonalDetails) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PersonalDetails) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *PersonalDetails) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PersonalDetails) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *PersonalDetails) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

// Relationship Data
type RelationshipData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RelatedUserId    string                 `protobuf:"bytes,3,opt,name=related_user_id,json=relatedUserId,proto3" json:"related_user_id,omitempty"`
	RelationshipType string                 `protobuf:"bytes,4,opt,name=relationship_type,json=relationshipType,proto3" json:"relationship_type,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RelationshipData) Reset() {
	*x = RelationshipData{}
	mi := &file_aaa_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipData) ProtoMessage() {}

func (x *RelationshipData) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipData.ProtoReflect.Descriptor instead.
func (*RelationshipData) Descriptor() ([]byte, []int) {
	return file_aaa_proto_rawDescGZIP(), []int{20}
}

func (x *RelationshipData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RelationshipData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RelationshipData) GetRelatedUserId() string {
	if x != nil {
		return x.RelatedUserId
	}
	return ""
}

func (x *RelationshipData) GetRelationshipType() string {
	if x != nil {
		return x.RelationshipType
	}
	return ""
}

func (x *RelationshipData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RelationshipData) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_aaa_proto protoreflect.FileDescriptor

const file_aaa_proto_rawDesc = "" +
	"\n" +
	"\taaa.proto\x12\x03aaa\"\x94\x01\n" +
	"\x13RegisterUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12#\n" +
	"\rmobile_number\x18\x03 \x01(\tR\fmobileNumber\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"\xc2\x01\n" +
	"\x14RegisterUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04data\x18\x03 \x01(\v2\r.aaa.UserDataR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x03(\tR\x05error\x12\x1f\n" +
	"\vstatus_code\x18\x05 \x01(\x05R\n" +
	"statusCode\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xbb\x01\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04data\x18\x03 \x01(\v2\r.aaa.UserDataR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x03(\tR\x05error\x12\x1f\n" +
	"\vstatus_code\x18\x05 \x01(\x05R\n" +
	"statusCode\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"-\n" +
	"\x12GetUserByIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xc1\x01\n" +
	"\x13GetUserByIdResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04data\x18\x03 \x01(\v2\r.aaa.UserDataR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x03(\tR\x05error\x12\x1f\n" +
	"\vstatus_code\x18\x05 \x01(\x05R\n" +
	"statusCode\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"C\n" +
	"\x1cGetUserByMobileNumberRequest\x12#\n" +
	"\rmobile_number\x18\x01 \x01(\tR\fmobileNumber\"\xcb\x01\n" +
	"\x1dGetUserByMobileNumberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04data\x18\x03 \x01(\v2\r.aaa.UserDataR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x03(\tR\x05error\x12\x1f\n" +
	"\vstatus_code\x18\x05 \x01(\x05R\n" +
	"statusCode\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"O\n" +
	"\x17AssignRoleToUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\"\xc6\x01\n" +
	"\x18AssignRoleToUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04data\x18\x03 \x01(\v2\r.aaa.UserDataR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x03(\tR\x05error\x12\x1f\n" +
	"\vstatus_code\x18\x05 \x01(\x05R\n" +
	"statusCode\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"\xb6\x01\n" +
	"\x13ValidateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x11validation_status\x18\x02 \x01(\tR\x10validationStatus\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12?\n" +
	"\x10personal_details\x18\x04 \x01(\v2\x14.aaa.PersonalDetailsR\x0fpersonalDetails\"\xc2\x01\n" +
	"\x14ValidateUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04data\x18\x03 \x01(\v2\r.aaa.UserDataR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x03(\tR\x05error\x12\x1f\n" +
	"\vstatus_code\x18\x05 \x01(\x05R\n" +
	"statusCode\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"\x89\x01\n" +
	"\x19CreateRelationshipRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x0frelated_user_id\x18\x02 \x01(\tR\rrelatedUserId\x12+\n" +
	"\x11relationship_type\x18\x03 \x01(\tR\x10relationshipType\"\xd0\x01\n" +
	"\x1aCreateRelationshipResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.aaa.RelationshipDataR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x03(\tR\x05error\x12\x1f\n" +
	"\vstatus_code\x18\x05 \x01(\x05R\n" +
	"statusCode\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"\\\n" +
	"\x19DeleteRelationshipRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x0frelated_user_id\x18\x02 \x01(\tR\rrelatedUserId\"\xa5\x01\n" +
	"\x1aDeleteRelationshipResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x03(\tR\x05error\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"\xf3\x01\n" +
	"\bUserData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12#\n" +
	"\rmobile_number\x18\x04 \x01(\tR\fmobileNumber\x12!\n" +
	"\fis_validated\x18\x05 \x01(\bR\visValidated\x12\x1f\n" +
	"\x05roles\x18\x06 \x03(\v2\t.aaa.RoleR\x05roles\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"V\n" +
	"\x04Role\x12\x1b\n" +
	"\trole_name\x18\x01 \x01(\tR\broleName\x121\n" +
	"\vpermissions\x18\x02 \x03(\v2\x0f.aaa.PermissionR\vpermissions\"B\n" +
	"\n" +
	"Permission\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x18\n" +
	"\aactions\x18\x02 \x03(\tR\aactions\"\xe9\x01\n" +
	"\x0fPersonalDetails\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\"\n" +
	"\rdate_of_birth\x18\x02 \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\b \x01(\tR\n" +
	"postalCode\"\xce\x01\n" +
	"\x10RelationshipData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12&\n" +
	"\x0frelated_user_id\x18\x03 \x01(\tR\rrelatedUserId\x12+\n" +
	"\x11relationship_type\x18\x04 \x01(\tR\x10relationshipType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt2\xe2\x04\n" +
	"\vUserService\x12C\n" +
	"\fRegisterUser\x12\x18.aaa.RegisterUserRequest\x1a\x19.aaa.RegisterUserResponse\x12.\n" +
	"\x05Login\x12\x11.aaa.LoginRequest\x1a\x12.aaa.LoginResponse\x12@\n" +
	"\vGetUserById\x12\x17.aaa.GetUserByIdRequest\x1a\x18.aaa.GetUserByIdResponse\x12^\n" +
	"\x15GetUserByMobileNumber\x12!.aaa.GetUserByMobileNumberRequest\x1a\".aaa.GetUserByMobileNumberResponse\x12I\n" +
	"\n" +
	"AssignRole\x12\x1c.aaa.AssignRoleToUserRequest\x1a\x1d.aaa.AssignRoleToUserResponse\x12C\n" +
	"\fValidateUser\x12\x18.aaa.ValidateUserRequest\x1a\x19.aaa.ValidateUserResponse\x12U\n" +
	"\x12CreateRelationship\x12\x1e.aaa.CreateRelationshipRequest\x1a\x1f.aaa.CreateRelationshipResponse\x12U\n" +
	"\x12DeleteRelationship\x12\x1e.aaa.DeleteRelationshipRequest\x1a\x1f.aaa.DeleteRelationshipResponseB&Z$github.com/kisanlink/protobuf/pb-aaab\x06proto3"

var (
	file_aaa_proto_rawDescOnce sync.Once
	file_aaa_proto_rawDescData []byte
)

func file_aaa_proto_rawDescGZIP() []byte {
	file_aaa_proto_rawDescOnce.Do(func() {
		file_aaa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aaa_proto_rawDesc), len(file_aaa_proto_rawDesc)))
	})
	return file_aaa_proto_rawDescData
}

var file_aaa_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_aaa_proto_goTypes = []any{
	(*RegisterUserRequest)(nil),           // 0: aaa.RegisterUserRequest
	(*RegisterUserResponse)(nil),          // 1: aaa.RegisterUserResponse
	(*LoginRequest)(nil),                  // 2: aaa.LoginRequest
	(*LoginResponse)(nil),                 // 3: aaa.LoginResponse
	(*GetUserByIdRequest)(nil),            // 4: aaa.GetUserByIdRequest
	(*GetUserByIdResponse)(nil),           // 5: aaa.GetUserByIdResponse
	(*GetUserByMobileNumberRequest)(nil),  // 6: aaa.GetUserByMobileNumberRequest
	(*GetUserByMobileNumberResponse)(nil), // 7: aaa.GetUserByMobileNumberResponse
	(*AssignRoleToUserRequest)(nil),       // 8: aaa.AssignRoleToUserRequest
	(*AssignRoleToUserResponse)(nil),      // 9: aaa.AssignRoleToUserResponse
	(*ValidateUserRequest)(nil),           // 10: aaa.ValidateUserRequest
	(*ValidateUserResponse)(nil),          // 11: aaa.ValidateUserResponse
	(*CreateRelationshipRequest)(nil),     // 12: aaa.CreateRelationshipRequest
	(*CreateRelationshipResponse)(nil),    // 13: aaa.CreateRelationshipResponse
	(*DeleteRelationshipRequest)(nil),     // 14: aaa.DeleteRelationshipRequest
	(*DeleteRelationshipResponse)(nil),    // 15: aaa.DeleteRelationshipResponse
	(*UserData)(nil),                      // 16: aaa.UserData
	(*Role)(nil),                          // 17: aaa.Role
	(*Permission)(nil),                    // 18: aaa.Permission
	(*PersonalDetails)(nil),               // 19: aaa.PersonalDetails
	(*RelationshipData)(nil),              // 20: aaa.RelationshipData
}
var file_aaa_proto_depIdxs = []int32{
	16, // 0: aaa.RegisterUserResponse.data:type_name -> aaa.UserData
	16, // 1: aaa.LoginResponse.data:type_name -> aaa.UserData
	16, // 2: aaa.GetUserByIdResponse.data:type_name -> aaa.UserData
	16, // 3: aaa.GetUserByMobileNumberResponse.data:type_name -> aaa.UserData
	16, // 4: aaa.AssignRoleToUserResponse.data:type_name -> aaa.UserData
	19, // 5: aaa.ValidateUserRequest.personal_details:type_name -> aaa.PersonalDetails
	16, // 6: aaa.ValidateUserResponse.data:type_name -> aaa.UserData
	20, // 7: aaa.CreateRelationshipResponse.data:type_name -> aaa.RelationshipData
	17, // 8: aaa.UserData.roles:type_name -> aaa.Role
	18, // 9: aaa.Role.permissions:type_name -> aaa.Permission
	0,  // 10: aaa.UserService.RegisterUser:input_type -> aaa.RegisterUserRequest
	2,  // 11: aaa.UserService.Login:input_type -> aaa.LoginRequest
	4,  // 12: aaa.UserService.GetUserById:input_type -> aaa.GetUserByIdRequest
	6,  // 13: aaa.UserService.GetUserByMobileNumber:input_type -> aaa.GetUserByMobileNumberRequest
	8,  // 14: aaa.UserService.AssignRole:input_type -> aaa.AssignRoleToUserRequest
	10, // 15: aaa.UserService.ValidateUser:input_type -> aaa.ValidateUserRequest
	12, // 16: aaa.UserService.CreateRelationship:input_type -> aaa.CreateRelationshipRequest
	14, // 17: aaa.UserService.DeleteRelationship:input_type -> aaa.DeleteRelationshipRequest
	1,  // 18: aaa.UserService.RegisterUser:output_type -> aaa.RegisterUserResponse
	3,  // 19: aaa.UserService.Login:output_type -> aaa.LoginResponse
	5,  // 20: aaa.UserService.GetUserById:output_type -> aaa.GetUserByIdResponse
	7,  // 21: aaa.UserService.GetUserByMobileNumber:output_type -> aaa.GetUserByMobileNumberResponse
	9,  // 22: aaa.UserService.AssignRole:output_type -> aaa.AssignRoleToUserResponse
	11, // 23: aaa.UserService.ValidateUser:output_type -> aaa.ValidateUserResponse
	13, // 24: aaa.UserService.CreateRelationship:output_type -> aaa.CreateRelationshipResponse
	15, // 25: aaa.UserService.DeleteRelationship:output_type -> aaa.DeleteRelationshipResponse
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_aaa_proto_init() }
func file_aaa_proto_init() {
	if File_aaa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aaa_proto_rawDesc), len(file_aaa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aaa_proto_goTypes,
		DependencyIndexes: file_aaa_proto_depIdxs,
		MessageInfos:      file_aaa_proto_msgTypes,
	}.Build()
	File_aaa_proto = out.File
	file_aaa_proto_goTypes = nil
	file_aaa_proto_depIdxs = nil
}
