// File: pkg/firebase/email.go

package firebase

import (
	"context"
	"fmt"
	"log"
	"os"

	firebase "firebase.google.com/go/v4"
	"firebase.google.com/go/v4/auth"
	"google.golang.org/api/option"
)

// EmailService handles sending emails via Firebase
type EmailService struct {
	client      *auth.Client
	app         *firebase.App
	frontendURL string
}

// NewEmailService initializes Firebase Admin SDK for email sending
func NewEmailService(credentialsPath, credentialsJSON, frontendURL string) (*EmailService, error) {
	ctx := context.Background()

	var opt option.ClientOption

	// Priority: JSON credentials (for containers) > file path (for local dev)
	if credentialsJSON != "" {
		log.Println("Initializing Firebase with base64 credentials from environment")
		opt = option.WithCredentialsJSON([]byte(credentialsJSON))
	} else if credentialsPath != "" {
		log.Printf("Initializing Firebase with credentials file: %s", credentialsPath)
		if _, err := os.Stat(credentialsPath); os.IsNotExist(err) {
			return nil, fmt.Errorf("firebase credentials file not found: %s", credentialsPath)
		}
		opt = option.WithCredentialsFile(credentialsPath)
	} else {
		return nil, fmt.Errorf("firebase credentials not provided: set FIREBASE_CREDENTIALS_PATH or FIREBASE_CREDENTIALS_JSON")
	}

	// Initialize Firebase App
	app, err := firebase.NewApp(ctx, nil, opt)
	if err != nil {
		return nil, fmt.Errorf("failed to initialize Firebase app: %w", err)
	}

	// Get Auth client
	client, err := app.Auth(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get Firebase Auth client: %w", err)
	}

	log.Println("✅ Firebase email service initialized successfully")

	return &EmailService{
		client:      client,
		app:         app,
		frontendURL: frontendURL,
	}, nil
}

// SendVerificationEmail sends an email verification link to the user
// The token is generated by our backend and passed to this function
func (s *EmailService) SendVerificationEmail(ctx context.Context, email, token string) error {
	log.Printf("📧 Sending verification email to: %s", email)

	// Construct verification link
	verificationLink := fmt.Sprintf("%s/verify-email?token=%s", s.frontendURL, token)

	// Note: Firebase Auth doesn't have a direct "send custom email" API
	// We need to use Firebase Auth's email verification, but with our own token
	// Alternative: Use Firebase Auth's generateEmailVerificationLink and parse the token
	// For now, we'll use a workaround with custom email templates

	// Get or create Firebase user (for email sending capability)
	_, err := s.client.GetUserByEmail(ctx, email)
	if err != nil {
		// User doesn't exist in Firebase, create a temporary one
		// This is just for email sending purposes
		params := (&auth.UserToCreate{}).Email(email).EmailVerified(false)
		_, err = s.client.CreateUser(ctx, params)
		if err != nil {
			return fmt.Errorf("failed to create Firebase user for email: %w", err)
		}
		log.Printf("Created temporary Firebase user for email: %s", email)
	}

	// Generate email verification link using Firebase
	actionCodeSettings := &auth.ActionCodeSettings{
		URL:             verificationLink,
		HandleCodeInApp: false,
	}

	link, err := s.client.EmailVerificationLinkWithSettings(ctx, email, actionCodeSettings)
	if err != nil {
		return fmt.Errorf("failed to generate verification link: %w", err)
	}

	log.Printf("✅ Email verification link generated: %s", link)
	log.Printf("⚠️  Note: Firebase will send the email automatically to: %s", email)

	return nil
}

// SendPasswordResetEmail sends a password reset link to the user
// The token is generated by our backend and passed to this function
func (s *EmailService) SendPasswordResetEmail(ctx context.Context, email, token string) error {
	log.Printf("📧 Sending password reset email to: %s", email)

	// Construct reset link
	resetLink := fmt.Sprintf("%s/reset-password?token=%s", s.frontendURL, token)

	// Get Firebase user
	_, err := s.client.GetUserByEmail(ctx, email)
	if err != nil {
		// Create user if doesn't exist (for email sending)
		params := (&auth.UserToCreate{}).Email(email).EmailVerified(true)
		_, err = s.client.CreateUser(ctx, params)
		if err != nil {
			return fmt.Errorf("failed to create Firebase user for password reset email: %w", err)
		}
		log.Printf("Created temporary Firebase user for password reset: %s", email)
	}

	// Generate password reset link using Firebase
	actionCodeSettings := &auth.ActionCodeSettings{
		URL:             resetLink,
		HandleCodeInApp: false,
	}

	link, err := s.client.PasswordResetLinkWithSettings(ctx, email, actionCodeSettings)
	if err != nil {
		return fmt.Errorf("failed to generate password reset link: %w", err)
	}

	log.Printf("✅ Password reset link generated: %s", link)
	log.Printf("⚠️  Note: Firebase will send the email automatically to: %s", email)

	return nil
}

// DeleteFirebaseUser deletes a Firebase user (cleanup helper)
func (s *EmailService) DeleteFirebaseUser(ctx context.Context, email string) error {
	userRecord, err := s.client.GetUserByEmail(ctx, email)
	if err != nil {
		return fmt.Errorf("user not found in Firebase: %w", err)
	}

	if err := s.client.DeleteUser(ctx, userRecord.UID); err != nil {
		return fmt.Errorf("failed to delete Firebase user: %w", err)
	}

	log.Printf("Deleted Firebase user: %s", email)
	return nil
}
